### ISSUE TITLE
Installation from Github Fails for Latest Version

### ISSUE THREAD

**Issue by WraySmith** [CentreForHydrology/Reanalysis#6]
Hi, I just tried installing the latest version of the Reanalysis package using:
- library(devtools)
- install_github("CentreForHydrology/Reanalysis")
However, the installation fails (see error messages below). Previously, I was able to install the package and I also had a colleague try and install the latest version and he received the same error message. It looks like a recent commit was made to the package and I wonder if it created an issue?

`install_github("CentreForHydrology/Reanalysis")
Downloading GitHub repo CentreForHydrology/Reanalysis@master
√  checking for file 'C:\Users\nsmith\AppData\Local\Temp\RtmpcLKd9F\remotescee04f2d54bb\CentreForHydrology-Reanalysis-19c20b0/DESCRIPTION' (440ms)
-  preparing 'Reanalysis':
√  checking DESCRIPTION meta-information ... 
   Warning: C:/Users/nsmith/AppData/Local/Temp/Rtmpa8SrtD/Rbuildd5c02a657e43/Reanalysis/man/NARRdownloadNetCDF.Rd:39: unexpected UNKNOWN '\item'
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  looking to see if a 'data/datalist' file should be added
-  building 'Reanalysis_1.3.1.tar.gz'
   
Installing package into ‘C:/Users/nsmith/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
* installing *source* package 'Reanalysis' ...
** using staged installation
** R
Error in parse(outFile) : 
  C:/Users/nsmith/AppData/Local/Temp/Rtmp69PBi8/R.INSTALLe54c12221d04/Reanalysis/R/NARRdownloadNetCDF.R:2:1: unexpected input
1: #' Downloads NARR NetCDF files
2: <<
   ^
ERROR: unable to collate and parse R files for package 'Reanalysis'
* removing 'C:/Users/nsmith/Documents/R/win-library/3.6/Reanalysis'
Error: Failed to install 'Reanalysis' from GitHub:
  (converted from warning) installation of package ‘C:/Users/nsmith/AppData/Local/Temp/RtmpcLKd9F/filecee0575b242c/Reanalysis_1.3.1.tar.gz’ had non-zero exit status`

**Comment by KevinShook** [comment]
Looks like the latest commit must have caused a problem.
I'll take a look at it.
Thanks for letting me know about it.

**Comment by KevinShook** [comment]
I see the issue. It looks like git introduced some lines when diffing files.
I'll fix it and will re-upload

**Comment by KevinShook** [comment]
Issue should now be fixed

**Comment by WraySmith** [comment]
Thanks, it looks like the updates were made in the Bastien branch so I installed using the Bastien branch as follows and it the install went through:
library(devtools)
install_github("CentreForHydrology/Reanalysis@Bastien")

**Comment by KevinShook** [comment]
Had to merge it with the main branch - should now be done.
Please let me know if it works
Thanks for the help

**Comment by WraySmith** [comment]
Yep, works from the master branch now. Thanks again!
